// scripts/constants.js
const CONSTANTS = {
  RECIPIENT_MEMBERS: [
    "3 Way Marketing Proprietary Limited",
    "Absa Bank Ltd",
    "Accelerated Digital Solutions (Pty) Ltd",
    "Advantagex Digital",
    "ADX DIGITAL",
    "Africa's Talking South Africa",
    "AfriGIS",
    "Airvantage (Pty) Ltd",
    "Allied LTD",
    "Always Active Technologies",
    "Appsland",
    "Arshiya",
    "Atlas Digital MEA",
    "Audiencenest PTE LTD",
    "Awesim Telecoms (Pty) Ltd",
    "Basebone",
    "Baseplay",
    "Beecell Digital Media",
    "BIDVEST DATA A DIVISION OF BIDVEST PAPERPLUS (PTY) LTD",
    "Black Moon Investments 7 (Pty) Ltd",
    "Blue Label Data Solutions",
    "Bopelo",
    "Broadsmart",
    "Bubble Bobble",
    "Buongiorno SA (Pty) Ltd",
    "Cartrack",
    "Celerity Systems t/a BulkSMS.com",
    "Cellfind",
    "Centpercent Technologies Private Limited",
    "CFM Content For Mobile Africa (Pty) Ltd",
    "Channel Mobile",
    "CityMobile and Telecommunications",
    "CLC AFRICA COMMUNITY LOYALTY CLUB",
    "Clear Moon",
    "Clickatell",
    "CM Telecom South Africa",
    "Collectcent Digital Media",
    "COLONY CAMPAIGNS (PTY) LTD",
    "Connect Mobile",
    "Connect SMS",
    "CONTENT CONNECT AFRICA (PTY) LTD",
    "Cookies Factory S.R.L",
    "Ctrack SA",
    "Data Discovery",
    "DCB Billing",
    "DCB Connect",
    "Delighten Technology Limited",
    "Delta Investments",
    "DigiCore Fleet Management",
    "Digital Material",
    "DIGITAL TECHNOLOGY LIMITED",
    "Digitalabs",
    "Dis-Chem Pharmacies",
    "Dotgo",
    "Dynamic Mobile Billing South Africa (Pty) Ltd",
    "Entersekt",
    "Everlytic",
    "Exceptional Rights",
    "Fanclash South Africa",
    "Fat Panda",
    "Flash Mobile Vending",
    "Foneworx",
    "Forest interactive",
    "FORMAL GRAND RESOURCES (PTY) LTD",
    "Gameloft",
    "GANTU",
    "GG Network LLC",
    "Globocom Infotech Pvt. Ltd.",
    "GM Europe Limited",
    "Grandcom",
    "Grapevine Interactive",
    "HAPPY APPS",
    "High Gable LTD",
    "HTP Digital Way",
    "Huawei Technologies",
    "Huge TNS (Pty) Ltd",
    "Hungama",
    "HYVEMobile",
    "iBurst",
    "Idea Rocket",
    "ILIVEIT",
    "IN10 Media Private Limited",
    "Indian Ocean Telecoms",
    "Infobip Africa",
    "Infotech RED",
    "Ingage Support",
    "Insidedata (Pty) Ltd",
    "INSIGHT DATA TECHNOLOGIES",
    "Inspiritum LTD",
    "Intarget Mobile Advertising (Pty) Ltd",
    "INTECH FZCO",
    "Interactive Telephony (Pty) Ltd",
    "Interband",
    "iTouch Messaging Services",
    "Ivorycell",
    "IWS",
    "JOKER MOBILE",
    "JS Mobile",
    "Jumpstart Interactive Intelligence (Pty) Ltd",
    "K&C",
    "Khumbula",
    "KMI CLOUD",
    "Lesaka Technologies (Pty) Ltd",
    "LogicSMS",
    "LRH Distribution",
    "Mandora",
    "Marvel Media",
    "MCR - Mobile Content Distribution",
    "Mdundo.com A/S",
    "MEDIA UNION",
    "Mobile Direct",
    "Mobile Minded B.V",
    "Mobile Software Digital Services",
    "Mobile World AG",
    "MobiMedia",
    "Mobistar",
    "Mobivate Limited",
    "Mobivixo",
    "Mobixone",
    "Mobliix",
    "Mondia Media SA",
    "Mr Messaging South Africa (Pty) Ltd",
    "MSF/Doctors Without Borders SA",
    "Mybeat Interactive",
    "NAZARA digital",
    "Ndoto Media",
    "Netsmart SA",
    "Netsport Mobile",
    "Newstar Business Solutions",
    "Newstor",
    "NEXT VIBE ENTERTAINMENT",
    "Nexus LTD",
    "Nitax Technologies Limited",
    "NTH MOBILE PTY",
    "OleConnect",
    "ONE10Labs",
    "OnePIN Inc",
    "OnMobile Global SA Ltd.",
    "Origindata",
    "PACE ONLINE PTY LTD",
    "Panacea Mobile",
    "Pattern Matched Technologies",
    "Plurisync (Pty) Ltd",
    "PM Connect Africa (Pty) Ltd",
    "Portutel",
    "Progressive 1",
    "PT.LINKIT",
    "Red October Technologies",
    "Renxo",
    "RFS Digital Solutions",
    "S P Two Ltd",
    "Saicom",
    "Sam Media Limited",
    "Shemaroo Entertainment Limited",
    "Simfy Africa",
    "SITA SOC Ltd",
    "SKY TO OCEAN SOLUTIONS (PTY)LTD STOS",
    "Smart Mobile Tech",
    "Smartphone",
    "SMS Cellular Services",
    "SMSFlow",
    "SMSolutions",
    "SMSPortal (Pty) Ltd",
    "STELLA ADS LLP.",
    "StreamPlay Solutions Pty Ltd",
    "STS (Smartcall Technology Solutions)",
    "SVMobi",
    "T-MOB International",
    "TauLite (Pty) Ltd",
    "TechVault Pte Ltd",
    "Telecoming",
    "Telecubes",
    "Telestream Communications (Pty) Ltd",
    "The Apprentice Valley Pty Ltd",
    "Thumbtribe",
    "TIC-IT Telecoms",
    "Timwetech",
    "Tracker",
    "TruTeq Wireless",
    "TT Mbha TV",
    "Twistbox Entertaiment",
    "U2OPIA MOBILE / Collective Networks",
    "Unlimited Gamez Inc.",
    "UPSTREAM SYSTEMS SOUTH AFRICA",
    "VENISO",
    "Vertical Service Provider (Pty) Ltd",
    "ViaMedia",
    "ViB Mobile SA",
    "Vibe Technologies",
    "Virtual Payment Solutions (Pty) Ltd",
    "Vivum Group",
    "Vodacom (Pty) Ltd (Internal Wasp)",
    "Vuclip",
    "W2mobile PTY LTD",
    "WAPLEAD SOLUTIONS LLC",
    "Whole Way Mobile Services",
    "WinSMS",
    "Wireless Waves SA LTD",
    "Worldplay",
    "www.imageperfect.in",
    "Xsparrow",
    "YellowDot Mobile",
    "Yola Media",
    "Yonder Media",
    "ZALTON",
    "Zed Mobile"
  ],

  NETWORKS: ["MTN", "Vodacom", "Cell C", "Telkom"],
  
  TEST_TYPES: ["Complete", "Partial"],
  
  TEST_RESULTS: ["Compliant", "Non-compliant", "Inconclusive"],
  
  WARNING_TYPES: [
    { value: "compliance", label: "Compliance Issue" },
    { value: "service", label: "Service Issue" },
    { value: "pricing", label: "Pricing Issue" },
    { value: "other", label: "Other" }
  ],

  USER_TABS: [
    { id: "tests", label: "Manual Tests" },
    { id: "upload", label: "Upload Manual Tests" },
    { id: "warnings", label: "Email Warnings" },
    { id: "export", label: "Export Data" }
  ],

  MANAGER_TABS: [
    { id: "overview", label: "👥 Overview" },
    { id: "stats", label: "📊 User Stats" },
    { id: "export", label: "📦 Export User Data" },
    { id: "admin", label: "⚙️ User Management" }
  ]
};

// Export to window
window.CONSTANTS = CONSTANTS;